# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_rmse <- function(x, y, byband) {
    .Call(`_cloudfil_cpp_rmse`, x, y, byband)
}

fill_image <- function(ref, cld, w, nrow, ncol) {
    .Call(`_cloudfil_fill_image`, ref, cld, w, nrow, ncol)
}

get_dist <- function(ngbs, i, w, nrow, ncol) {
    .Call(`_cloudfil_get_dist`, ngbs, i, w, nrow, ncol)
}

get_edge <- function(i, w, ncols, nrows) {
    .Call(`_cloudfil_get_edge`, i, w, ncols, nrows)
}

get_ngbs <- function(i, w, nrow, ncol) {
    .Call(`_cloudfil_get_ngbs`, i, w, nrow, ncol)
}

